version: "3.8"
services:
    client:
        build:
            context: ./src
            dockerfile: client/docker/Dockerfile
        env_file:
            - .env
        ports:
            - 8000:8000

    server:
        build:
            context: ./src
            dockerfile: server/docker/Dockerfile
        env_file:
            - .env
        ports:
            - 50051:50051
