# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: song_generator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import song_generator.base_pb2 as base__pb2
import song_generator.enums_pb2 as enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14song_generator.proto\x1a\nbase.proto\x1a\x0b\x65nums.proto\"\x7f\n\x16MakeMeSuperstarRequest\x12 \n\x08\x63\x61tegory\x18\x01 \x01(\x0e\x32\x0e.MusicCategory\x12\x13\n\x0bsongs_count\x18\x02 \x01(\x05\x12\x13\n\x0bsongs_theme\x18\x03 \x01(\t\x12\x19\n\x11\x63over_description\x18\x04 \x01(\t2E\n\rSongGenerator\x12\x34\n\x11make_me_superstar\x12\x17.MakeMeSuperstarRequest\x1a\x06.Albumb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'song_generator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAKEMESUPERSTARREQUEST._serialized_start=49
  _MAKEMESUPERSTARREQUEST._serialized_end=176
  _SONGGENERATOR._serialized_start=178
  _SONGGENERATOR._serialized_end=247
# @@protoc_insertion_point(module_scope)
